### ISSUE TITLE
Map is not being updated

### ISSUE THREAD

**Issue by jchoi25** [aayu3/UIUCCrimeMap#43]
I suspect that the map is only being updated when the map gets deployed (when we merge a new pull request). I have purposely not made any commits for the past two weeks and now the map does not have any recent data. I think we need to find a way to make the map re-deploy itself every 24 hours.

**Comment by aayu3** [comment]
Uh actually it just only gets updated when Illia manually updates it.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

From: Juyoung ***@***.***>
Sent: Thursday, July 1, 2021 3:31 PM
To: ***@***.***>
Cc: ***@***.***>
Subject: [aayu3/UIUCCrimeMap] Map is not being updated (#43)


I suspect that the map is only being updated when the map gets deployed (when we merge a new pull request). I have purposely not made any commits for the past two weeks and now the map does not have any recent data. I think we need to find a way to make the map re-deploy itself every 24 hours.

**Comment by jchoi25** [comment]
Okay so that is the case then. Still could there be a way that it gets updated automatically? While manually updating is fine with me, crime data from the past three weeks are missing and we may want to prevent that from happening when people actually start using this.
